In [1]:
import pandas as pd
from fxpmath import Fxp

In [2]:
def convert(x):
    y = Fxp(x, signed=True, dtype='S4.12')

    return int(y.bin(frac_dot=False), 2)

In [3]:
df = pd.read_csv('winequality-red.csv')
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [4]:
df.dropna
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [5]:
df.insert(0, 'quality', df.pop('quality'))

In [6]:
df=(df-df.min())/(df.max()-df.min())
df

,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,0.4,0.247788,0.397260,0.00,0.068493,0.106845,0.140845,0.098940,0.567548,0.606299,0.137725,0.153846
1,0.4,0.283186,0.520548,0.00,0.116438,0.143573,0.338028,0.215548,0.494126,0.362205,0.209581,0.215385
2,0.4,0.283186,0.438356,0.04,0.095890,0.133556,0.197183,0.169611,0.508811,0.409449,0.191617,0.215385
3,0.6,0.584071,0.109589,0.56,0.068493,0.105175,0.225352,0.190813,0.582232,0.330709,0.149701,0.215385
4,0.4,0.247788,0.397260,0.00,0.068493,0.106845,0.140845,0.098940,0.567548,0.606299,0.137725,0.153846
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,0.4,0.141593,0.328767,0.08,0.075342,0.130217,0.436620,0.134276,0.354626,0.559055,0.149701,0.323077
1595,0.6,0.115044,0.294521,0.10,0.089041,0.083472,0.535211,0.159011,0.370778,0.614173,0.257485,0.430769
1596,0.6,0.150442,0.267123,0.13,0.095890,0.106845,0.394366,0.120141,0.416300,0.535433,0.251497,0.400000
1597,0.4,0.115044,0.359589,0.12,0.075342,0.105175,0.436620,0.134276,0.396476,0.653543,0.227545,0.276923
1598,0.6,0.123894,0.130137,0.47,0.184932,0.091820,0.239437,0.127208,0.397944,0.511811,0.197605,0.400000

In [7]:
lines = []
for index, row in df.iterrows():
    x = []
    for j in row:
        x.append(str(hex(convert(j)))[2:])
    lines.append(' '.join(x))

In [8]:
lines = lines[:10]
# print(lines)
with open('..\\sim_1\\new\\mem2.mem', 'w') as f:
    f.write('\n'.join(lines))

In [9]:
3f 65 0 11 1b 24 19 91 9b 23 27 66 
48 85 0 1d 24 56 37 7e 5c 35 37 66 
48 70 a 18 22 32 2b 82 68 31 37 66 
95 1c 8f 11 1a 39 30 95 54 26 37 99 
3f 65 0 11 1b 24 19 91 9b 23 27 66 
3f 5e 0 f 1a 2b 1e 91 9b 23 27 66 
4a 54 f c 18 32 2f 76 70 13 27 66 
3d 5c 0 5 16 32 d 55 83 15 3f cc 
48 50 5 13 1a 1c a 7e 7c 24 2b cc 
41 42 5c 5b 19 39 56 91 7a 48 52

SyntaxError: invalid syntax (410971837.py, line 1)